### ISSUE TITLE
Comentarios sobre el ejercicio

### ISSUE THREAD

**Issue by m4n50n** [jgonzalez-89/Instagram-Photo-Feed-HTML-CSS#1]
Hola Jose,

✔ bien el ejercicio en general, aunque hay varias cosas que podrías corregir:

1. Si veo la web con una resolución menor, me aparece así:
![image](https://user-images.githubusercontent.com/92524023/201518532-d9f78ce7-8d77-46d6-957c-2b85acd2e7cf.png)

En cuanto al tamaño de la columna o del texto de debajo de la imagen no pasa nada porque como ya sabemos, con bootstrap sería muy fácil controlarlo, pero la imagen siempre tendría que verse bien. Esto consigues controlarlo usando las propiedades `object-fit` y `object-position`: https://css-tricks.com/on-object-fit-and-object-position/
![image](https://user-images.githubusercontent.com/92524023/201518631-cbf69bd1-457e-41d2-8f92-d8f9696860d0.png)

2. En `.flex-container` has usado `overflow-y: scroll;`. Esto fuerza la aparición de un scroll horizontal y provoca esto:
![image](https://user-images.githubusercontent.com/92524023/201518706-924a7aef-249b-4b4a-8635-09aa8db157b9.png)

Me aparece este scroll y el del navegador, por lo que se ve mal. Esta propiedad se usa en casos muy concretos, ya que por lo general el navegador va a mostrar su propio scroll siempre que haya contenido que no quepa en la pantalla.

3. Para alinear los elementos de la cabecera `.card_title` y `card_number` podrías haber usado también flexbox, ya que hoy día no te recomiendo hacer uso de _float_ y _width_ para alinear elementos y forzar que se muevan a un extremo u otro (https://css-tricks.com/snippets/css/a-guide-to-flexbox/)

**Comment by jgonzalez-89** [comment]
Corregido, muchas gracias!
